title: iNUX Jupyter Notebooks
description: An overview about iNUX Jupyter Notebooks and Streamlit Apps for interactive education
theme: just-the-docs

url: https://gw-inux.github.io/Jupyter-Notebooks/

aux_links:
  Template Repository: https://github.com/gw-inux/Jupyter-Notebooks
