name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Allows manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send keep-alive request
        run: |
          curl -s -o /dev/null -w "%{http_code}" "https://gwp-wellcapture.streamlit.app/"

